import {
  Activity,
  BadgeCheck,
  CalendarDays,
  ChartColumn,
  CircleCheck,
  CircleUser,
  ClipboardList,
  CloudRain,
  Database,
  Droplet,
  FileText,
  Gauge,
  HandHeart,
  Landmark,
  Layers,
  LifeBuoy,
  ListChecks,
  Map,
  MapPinned,
  MessageSquare,
  NotebookPen,
  Phone,
  Radar,
  Radio,
  Server,
  ShieldAlert,
  Siren,
  Target,
  Timer,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  Users,
  UsersRound,
  Warehouse,
  WavesArrowUp,
  Wind,
} from "lucide-react";

/** Resolve icon names serialized through the service layer → components */
export const ICONS = {
  Activity, BadgeCheck, CalendarDays, ChartColumn, CircleCheck, CircleUser, ClipboardList, CloudRain, Database, Droplet,
  FileText, Gauge, HandHeart, Landmark, Layers, LifeBuoy, ListChecks, Map, MapPinned, MessageSquare,
  NotebookPen, Phone, Radar, Radio, Server, ShieldAlert, Siren, Target, Timer, TrendingUp, TriangleAlert,
  UserCheck, Users, UsersRound, Warehouse, WavesArrowUp, Wind,
};

export const iconOf = (name, fallback = FileText) => ICONS[name] || fallback;
